### ISSUE TITLE
after DNS switch to 1.1.1.1 and 1.0.0.1, can not visit Github

### ISSUE THREAD

**Issue by dicksonboy** [cloudflare/1.1.1.1#101]
after DNS switch to 1.1.1.1 and 1.0.0.1, can not visit Github

**Comment by dhruvkrishnavaid** [comment]
Hi, I am Dhruv Krishna Vaid from India.
I have also tried to change my network's dns setings to 1.1.1.1 and 1.0.0.1 
However, I didn't face such issues and everything is working fine.
Have you tried setting both IPv4 and IPv6 addresses?
Click [here](https://1.1.1.1/dns/) for proper instructions for setting up dns.
Hope it helps.

**Comment by TownLake** [comment]
Apologies for the delayed response. @dicksonboy can you let us know if this is still an issue? If so, can you tell us the ISP that you use and any other details that can help us investigate. Happy to reopen.
