### ISSUE TITLE
1.1.1.1 warp connecting then disconnecting

### ISSUE THREAD

**Issue by TsukasaHinata** [cloudflare/1.1.1.1#155]
This is my first time using 1.1.1.1 warp 
when i was trying to connect it 
it connected
then disconnected
it might be of windows firewall
but im not sure
if anyone could answer my answer that would be greatly appreciated!

**Comment by kkrum** [comment]
Please file a bug with via the in-app bug icon. This will include debug information we can use to help figure out the problem

**Comment by Hooudini** [comment]
having the same issue i have tried everything a small mind could do but with no luck

**Comment by elithrar** [comment]
Hi folks - the most helpful things you can do:

- Make sure you have the latest version of the app!
- Don't run other VPN or network related software at the same time
- Report bugs via the app (top right); these reports include debug information that helps us better identify and fix issues.

Thanks!

Note: this GitHub repo is for our website - I'm going to close this out here.
