### ISSUE TITLE
[Error] Wrong size

### ISSUE THREAD

**Issue by OfficialMarinho** [cloudflare/1.1.1.1#89]
The landing page is the wrong size, or missing content in it's total space.

Print screen: https://imgur.com/a/NpqpsYM

**Comment by jensechu** [comment]
@OfficialMarinho Thanks for opening an issue! Are you able to provide steps to reproduce this?

**Comment by OfficialMarinho** [comment]
> @OfficialMarinho Thanks for opening an issue! Are you able to provide steps to reproduce this?

Yep, this GIF can help you: https://imgur.com/a/IVlpRki

**Browser:** Google Chrome
**OS:** Linux Mint
**Screen resolution:** 1366x768 (16:9)

**Comment by OfficialMarinho** [comment]
@jensechu Did you have some update about it?

**Comment by jensechu** [comment]
Oh. This is not a bug I think it was a design choice. 😄
